title: 'Donate 1 Meal and help stop hunger now!'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9212766
  brandStrength: 0
  lightness: 0.9106383
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-73838438-1
  facebook: null
favicon: null
name: Donate1meal
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3361702
layout_spectrum: 0.7595745
